### ISSUE TITLE
Support Buildkite plugin renovation

### ISSUE THREAD

**Issue by KevinGrandon** [renovateapp/renovate#1869]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

[Buildkite](http://buildkite.com/) is a provider of continuous integration services. Buildkite allows folks to use plugins within their build pipelines and you can find documentation on them here: https://buildkite.com/docs/agent/v3/plugins. Plugins are defined in the pipeline file (yaml) and they look like:
```yaml
steps:
  # Prebuild the app image, upload it to a registry for later steps
  - name: "Docker Build"
    plugins:
      docker-compose#v1.3.2:
        build: app
        image-repository: index.docker.io/org/repo
```

The plugin name is either a reference to a git repo, or a repo in the `buildkite-plugins` repository. The example above points to this repository: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin

It would be great if we could:
* Renovate all yaml files that have plugin references in the .buildkite/ folder.
* Have a configuration to match pipeline files not inside of the .buildkite/ folder and renovate them.

Happy to help contribute or collaborate on a solution if one would be accepted.
