### ISSUE TITLE
Node Support Policy Wipes Travis Configuration

### ISSUE THREAD

**Issue by hbetts** [renovateapp/renovate#2087]
**What Renovate type are you using?**

Renovate GitHub App

**Describe the bug**

Our `conventional-changelog` mono-repository is setup with the following `node` support policy:

```json
"node": {
  "enabled": true,
  "supportPolicy": ["lts", "current"]
},
```

Our `.travis.yml` configuration file:

```yaml
language: node_js
 
node_js:
  - 6
  - 8

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules/
    - ${HOME}/.npm

before_install:
  - npm install --global npm@latest

before_script:
  - git config --global user.name 'CI'
  - git config --global user.email 'dummy@example.org'

script:
  - npm test

after_script:
  - nyc report --reporter=text-lcov | coveralls
```

Is getting replaced with:

```yaml
 language: node_js
 
 node_js:
  - '8'
  - '6'
  - '10'
```

Our custom scripts are required for our unit tests to execute.

Here's the relevant pull request - https://github.com/conventional-changelog/conventional-changelog/pull/333

**To Reproduce**

1.  Fork the `conventional-changelog` mono-repository

**Expected behavior**

I would expect _just_ the `node_js` section to be updated with a new list of Node versions, and for all other sections to be left as was.
