### ISSUE TITLE
Support Docker Compose file renovation

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#832]
Renovate the "image" lines in a docker compose file. Apart from the file syntax, never everything else should be the same as the existing `Dockerfile` renovation.

Use a new manager name `docker-compose` instead of overloading the existing `docker` manager type, but apply config from the `docker` config type.

**Comment by rarkins** [comment]
Example:
```yml
# docker-compose.yml
version: '3'
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "26432:5432"
    environment:
      - POSTGRES_PASSWORD=hidden
  redis:
    container_name: redis
    image: redis
    ports:
      - "36379:6379"
  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "18081:8081"
    links:
      - db:postgres
    environment:
      - DATABASE_URL=postgres://postgres:hidden@postgres:5432/postgres?sslmode=disable
    depends_on:
      - db
  broker:
    image: rabbitmq:3-management
    ports:
      - "26672:5672" # main port
      - "27672:15672" # management port
```
